-- MySQL Script generated by MySQL Workbench
-- Sun Jun  4 12:45:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema home_work_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS home_work_1 ;

-- -----------------------------------------------------
-- Schema home_work_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS home_work_1 DEFAULT CHARACTER SET utf8 ;
USE home_work_1 ;

-- -----------------------------------------------------
-- Table home_work_1.developers
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.developers ;

CREATE TABLE IF NOT EXISTS home_work_1.developers (
  id_developers INT NOT NULL AUTO_INCREMENT,
  developer_name VARCHAR(45) NOT NULL,
  developer_age INT NOT NULL,
  PRIMARY KEY (id_developers),
  UNIQUE INDEX id_developers_UNIQUE (id_developers ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.skills
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.skills ;

CREATE TABLE IF NOT EXISTS home_work_1.skills (
  id_skills INT NOT NULL AUTO_INCREMENT,
  skill_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_skills),
  UNIQUE INDEX id_skills_UNIQUE (id_skills ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.projects
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.projects ;

CREATE TABLE IF NOT EXISTS home_work_1.projects (
  id_projects INT NOT NULL AUTO_INCREMENT,
  project_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_projects))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.companies
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.companies ;

CREATE TABLE IF NOT EXISTS home_work_1.companies (
  id_companies INT NOT NULL AUTO_INCREMENT,
  companie_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_companies),
  UNIQUE INDEX companie_name_UNIQUE (companie_name ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.customers
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.customers ;

CREATE TABLE IF NOT EXISTS home_work_1.customers (
  id_customers INT NOT NULL AUTO_INCREMENT,
  customer_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_customers),
  UNIQUE INDEX id_customers_UNIQUE (id_customers ASC),
  UNIQUE INDEX customer_name_UNIQUE (customer_name ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.developers_has_skills
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.developers_has_skills ;

CREATE TABLE IF NOT EXISTS home_work_1.developers_has_skills (
  developers_id_developers INT NOT NULL,
  skills_id_skills INT NOT NULL,
  PRIMARY KEY (developers_id_developers, skills_id_skills),
  INDEX fk_developers_has_skills_skills1_idx (skills_id_skills ASC),
  INDEX fk_developers_has_skills_developers_idx (developers_id_developers ASC),
  CONSTRAINT fk_developers_has_skills_developers
    FOREIGN KEY (developers_id_developers)
    REFERENCES home_work_1.developers (id_developers)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_developers_has_skills_skills1
    FOREIGN KEY (skills_id_skills)
    REFERENCES home_work_1.skills (id_skills)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.companies_has_developers
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.companies_has_developers ;

CREATE TABLE IF NOT EXISTS home_work_1.companies_has_developers (
  companies_id_companies INT NOT NULL,
  developers_id_developers INT NOT NULL,
  PRIMARY KEY (companies_id_companies, developers_id_developers),
  INDEX fk_companies_has_developers_developers1_idx (developers_id_developers ASC),
  INDEX fk_companies_has_developers_companies1_idx (companies_id_companies ASC),
  CONSTRAINT fk_companies_has_developers_companies1
    FOREIGN KEY (companies_id_companies)
    REFERENCES home_work_1.companies (id_companies)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_companies_has_developers_developers1
    FOREIGN KEY (developers_id_developers)
    REFERENCES home_work_1.developers (id_developers)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.companies_has_projects
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.companies_has_projects ;

CREATE TABLE IF NOT EXISTS home_work_1.companies_has_projects (
  companies_id_companies INT NOT NULL,
  projects_id_projects INT NOT NULL,
  PRIMARY KEY (companies_id_companies, projects_id_projects),
  INDEX fk_companies_has_projects_projects1_idx (projects_id_projects ASC),
  INDEX fk_companies_has_projects_companies1_idx (companies_id_companies ASC),
  CONSTRAINT fk_companies_has_projects_companies1
    FOREIGN KEY (companies_id_companies)
    REFERENCES home_work_1.companies (id_companies)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_companies_has_projects_projects1
    FOREIGN KEY (projects_id_projects)
    REFERENCES home_work_1.projects (id_projects)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.projects_has_customers
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.projects_has_customers ;

CREATE TABLE IF NOT EXISTS home_work_1.projects_has_customers (
  projects_id_projects INT NOT NULL,
  customers_id_customers INT NOT NULL,
  PRIMARY KEY (projects_id_projects, customers_id_customers),
  INDEX fk_projects_has_customers_customers1_idx (customers_id_customers ASC),
  INDEX fk_projects_has_customers_projects1_idx (projects_id_projects ASC),
  CONSTRAINT fk_projects_has_customers_projects1
    FOREIGN KEY (projects_id_projects)
    REFERENCES home_work_1.projects (id_projects)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_projects_has_customers_customers1
    FOREIGN KEY (customers_id_customers)
    REFERENCES home_work_1.customers (id_customers)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table home_work_1.projects_has_developers
-- -----------------------------------------------------
DROP TABLE IF EXISTS home_work_1.projects_has_developers ;

CREATE TABLE IF NOT EXISTS home_work_1.projects_has_developers (
  projects_id_projects INT NOT NULL,
  developers_id_developers INT NOT NULL,
  PRIMARY KEY (projects_id_projects, developers_id_developers),
  INDEX fk_projects_has_developers_developers1_idx (developers_id_developers ASC),
  INDEX fk_projects_has_developers_projects1_idx (projects_id_projects ASC),
  CONSTRAINT fk_projects_has_developers_projects1
    FOREIGN KEY (projects_id_projects)
    REFERENCES home_work_1.projects (id_projects)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_projects_has_developers_developers1
    FOREIGN KEY (developers_id_developers)
    REFERENCES home_work_1.developers (id_developers)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
